const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),uid=()=>crypto.randomUUID?.()||Date.now()+"-"+Math.random().toString(16).slice(2);
export function mountFlow(root,{store,onNotify,cloud}={}){
 const KEY="td:flows:v2",legacy=store?.get("td:flow:v1",null);
 let db=store?.get(KEY,null);if(cloud?.initial?.length){const remote=cloud.initial.map(r=>({id:r.id,name:r.name,createdAt:Date.parse(r.created_at)||Date.now(),updatedAt:Date.parse(r.updated_at)||Date.now(),nodes:r.document?.nodes||[],edges:r.document?.edges||[]}));const local=db?.flows||[];const merged=[...remote,...local.filter(l=>!remote.some(r=>r.id===l.id))];db={active:remote[0]?.id||merged[0]?.id,flows:merged}}if(!db?.flows?.length){const id=uid();db={active:id,flows:[{id,name:"Meu primeiro fluxo",createdAt:Date.now(),updatedAt:Date.now(),nodes:legacy?.nodes||[],edges:legacy?.edges||[]}]};}
 let doc=db.flows.find(x=>x.id===db.active)||db.flows[0],selected=null,selectedEdge=null,mode="select",drag=null,connectFrom=null,pan={x:0,y:0},zoom=1,dpr=devicePixelRatio||1,history=[],future=[];
 const persist=()=>{doc.updatedAt=Date.now();db.active=doc.id;store?.set(KEY,db)},snapshot=()=>JSON.stringify({nodes:doc.nodes,edges:doc.edges}),checkpoint=()=>{history.push(snapshot());if(history.length>50)history.shift();future=[]};
 const notify=(m,i)=>onNotify?.(m,i),confirmBox=async(o)=>window.Swal?(await Swal.fire({background:"#080808",color:"#fff",confirmButtonColor:"#fff",cancelButtonColor:"#181818",...o})).isConfirmed:confirm(o.title||"Confirmar?");
 root.innerHTML=`<div class="flow-app"><aside class="flow-docs"><div class="flow-docs-head"><strong>Meus fluxos</strong><button data-act="new-flow" title="Novo fluxo">＋</button></div><div id="flowList"></div><div class="flow-docs-foot"><button data-act="import">Importar JSON</button><input id="flowImport" type="file" accept="application/json" hidden></div></aside><section class="flow-work"><div class="flow-topbar"><div class="flow-title"><input id="flowName" maxlength="80"><small id="flowSaved">Salvo</small></div><div class="flow-actions"><button data-act="undo" title="Desfazer">↶</button><button data-act="redo" title="Refazer">↷</button><button data-act="export-json" title="Exportar JSON">JSON</button><button data-act="export-png" title="Exportar imagem">PNG</button><button data-act="delete-flow" class="flow-danger" title="Excluir fluxo">⌫</button></div></div><div class="flow-editor"><div class="flow-toolbar"><button data-mode="select" class="active" title="Selecionar (V)">↖</button><button data-mode="node" title="Retângulo / bloco (N)">□</button><button data-act="decision" title="Decisão / losango">◇</button><button data-act="note" title="Nota">○</button><button data-mode="connect" title="Seta / conexão (C)">→</button><button data-act="text" title="Texto">A</button><button data-mode="delete" title="Borracha / excluir">⌫</button><span class="flow-tool-divider"></span><button data-act="undo" title="Desfazer">↶</button><button data-act="redo" title="Refazer">↷</button></div><div class="flow-stage"><canvas id="flowCanvas"></canvas><div class="flow-zoom"><button data-act="zoom-out">−</button><button id="zoomLabel" data-act="zoom-reset">100%</button><button data-act="zoom-in">＋</button><button data-act="fit" title="Enquadrar">⌗</button></div><div class="flow-help">Escolha uma ferramenta e comece a desenhar · duplo clique cria um bloco</div></div><aside class="flow-properties" id="flowProps"><div class="flow-empty"><strong>Propriedades</strong><p>Selecione um elemento para editar.</p></div></aside></div></section></div>`;
 const canvas=root.querySelector("#flowCanvas"),ctx=canvas.getContext("2d"),stage=canvas.parentElement,$=s=>root.querySelector(s),$$=s=>[...root.querySelectorAll(s)];
 let cloudTimer=null;const save=(msg)=>{persist();$("#flowSaved").textContent=cloud?"Sincronizando…":"Salvo";renderList();if(cloud){clearTimeout(cloudTimer);cloudTimer=setTimeout(async()=>{try{const row=await cloud.onSave?.(doc);if(row?.id&&row.id!==doc.id){const old=doc.id;doc.id=row.id;db.active=row.id;db.flows.forEach(f=>{if(f.id===old)f.id=row.id});persist()}$("#flowSaved").textContent="Salvo na nuvem"}catch(e){console.error("Flow sync:",e);$("#flowSaved").textContent="Salvo local · sincronização pendente";notify(e?.message||"Falha ao sincronizar fluxo","error")}},900)}if(msg)notify(msg)};
 const renderList=()=>{$("#flowList").innerHTML=db.flows.map(f=>`<button class="flow-doc ${f.id===doc.id?"active":""}" data-doc="${f.id}"><span>${escapeHtml(f.name)}</span><small>${f.nodes.length} blocos</small></button>`).join("");$$("[data-doc]").forEach(b=>b.onclick=()=>switchDoc(b.dataset.doc))};
 const escapeHtml=s=>{const d=document.createElement("div");d.textContent=s??"";return d.innerHTML};
 const resize=()=>{const r=stage.getBoundingClientRect();canvas.width=Math.max(1,r.width*dpr);canvas.height=Math.max(1,r.height*dpr);canvas.style.width=r.width+"px";canvas.style.height=r.height+"px";draw()};
 const world=e=>{const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left-pan.x)/zoom,y:(e.clientY-r.top-pan.y)/zoom}},hit=p=>[...doc.nodes].reverse().find(n=>p.x>=n.x&&p.x<=n.x+n.w&&p.y>=n.y&&p.y<=n.y+n.h);
 const addNode=(x,y,title="Novo bloco")=>{checkpoint();const n={id:uid(),x,y,w:190,h:82,title,description:"",type:"process"};doc.nodes.push(n);selected=n.id;save();draw();renderProps();return n};
 const removeSelected=()=>{if(selected){checkpoint();doc.nodes=doc.nodes.filter(n=>n.id!==selected);doc.edges=doc.edges.filter(e=>e.a!==selected&&e.b!==selected);selected=null;save("Elemento excluído");draw();renderProps()}else if(selectedEdge){checkpoint();doc.edges=doc.edges.filter(e=>e.id!==selectedEdge);selectedEdge=null;save("Conexão excluída");draw()}};
 function draw(){ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,canvas.width/dpr,canvas.height/dpr);ctx.save();ctx.translate(pan.x,pan.y);ctx.scale(zoom,zoom);const W=canvas.width/dpr/zoom,H=canvas.height/dpr/zoom,step=28;ctx.strokeStyle="#151515";ctx.lineWidth=1/zoom;for(let x=(-pan.x/zoom)%step;x<W;x+=step){ctx.beginPath();ctx.moveTo(x,-pan.y/zoom);ctx.lineTo(x,H-pan.y/zoom);ctx.stroke()}for(let y=(-pan.y/zoom)%step;y<H;y+=step){ctx.beginPath();ctx.moveTo(-pan.x/zoom,y);ctx.lineTo(W-pan.x/zoom,y);ctx.stroke()}doc.edges.forEach(e=>{const a=doc.nodes.find(n=>n.id===e.a),b=doc.nodes.find(n=>n.id===e.b);if(!a||!b)return;const ax=a.x+a.w,ay=a.y+a.h/2,bx=b.x,by=b.y+b.h/2,m=(ax+bx)/2;ctx.strokeStyle=e.id===selectedEdge?"#fff":"#6c6c6c";ctx.lineWidth=(e.id===selectedEdge?3:2)/zoom;ctx.beginPath();ctx.moveTo(ax,ay);ctx.bezierCurveTo(m,ay,m,by,bx,by);ctx.stroke();ctx.fillStyle=ctx.strokeStyle;ctx.beginPath();ctx.arc(bx,by,4/zoom,0,Math.PI*2);ctx.fill()});doc.nodes.forEach(n=>{ctx.shadowColor=n.id===selected?"#ffffff35":"transparent";ctx.shadowBlur=n.id===selected?18:0;ctx.beginPath();ctx.roundRect(n.x,n.y,n.w,n.h,14);ctx.fillStyle=n.type==="decision"?"#101010":"#080808";ctx.fill();ctx.strokeStyle=n.id===selected?"#fff":"#343434";ctx.lineWidth=(n.id===selected?2:1)/zoom;ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle="#fff";ctx.font="600 14px DM Sans";ctx.fillText(n.title.slice(0,24),n.x+16,n.y+31);ctx.fillStyle="#777";ctx.font="12px DM Sans";ctx.fillText((n.description||n.type).slice(0,28),n.x+16,n.y+54)});ctx.restore();$("#zoomLabel").textContent=Math.round(zoom*100)+"%"}
 function renderProps(){const p=$("#flowProps"),n=doc.nodes.find(x=>x.id===selected);if(!n){p.innerHTML=`<div class="flow-empty"><strong>Propriedades</strong><p>Selecione um bloco para editar.</p></div>`;return}p.innerHTML=`<div class="flow-props-head"><strong>Propriedades</strong><button data-prop="duplicate">Duplicar</button></div><label>Título<input id="propTitle" maxlength="80" value="${escapeHtml(n.title)}"></label><label>Descrição<textarea id="propDesc" maxlength="180">${escapeHtml(n.description||"")}</textarea></label><label>Tipo<select id="propType"><option value="process">Processo</option><option value="decision">Decisão</option><option value="note">Nota</option></select></label><div class="flow-size"><label>Largura<input id="propW" type="number" min="120" max="420" value="${n.w}"></label><label>Altura<input id="propH" type="number" min="60" max="240" value="${n.h}"></label></div><button class="flow-delete-prop" data-prop="delete">Excluir bloco</button>`;$("#propType").value=n.type||"process";["propTitle","propDesc","propType","propW","propH"].forEach(id=>$("#"+id).onchange=()=>{checkpoint();n.title=$("#propTitle").value.trim()||"Sem título";n.description=$("#propDesc").value.trim();n.type=$("#propType").value;n.w=clamp(+$("#propW").value||190,120,420);n.h=clamp(+$("#propH").value||82,60,240);save();draw()});$('[data-prop="duplicate"]').onclick=()=>{checkpoint();const cp={...n,id:uid(),x:n.x+30,y:n.y+30,title:n.title+" cópia"};doc.nodes.push(cp);selected=cp.id;save("Bloco duplicado");draw();renderProps()};$('[data-prop="delete"]').onclick=removeSelected}
 function switchDoc(id){const next=db.flows.find(f=>f.id===id);if(!next)return;doc=next;db.active=id;selected=null;selectedEdge=null;pan={x:0,y:0};zoom=1;persist();$("#flowName").value=doc.name;renderList();renderProps();draw()}
 function restore(s){const x=JSON.parse(s);doc.nodes=x.nodes;doc.edges=x.edges;selected=null;selectedEdge=null;save();draw();renderProps()}
 function download(blob,name){const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
 async function action(a){if(a==="decision"||a==="note"||a==="text"){const r=stage.getBoundingClientRect(),p={x:(r.width/2-pan.x)/zoom,y:(r.height/2-pan.y)/zoom},n=addNode(p.x-95,p.y-41,a==="text"?"Texto":a==="decision"?"Decisão":"Nota");n.type=a==="text"?"note":a;save();draw();renderProps();}else if(a==="new-flow"){const res=window.Swal?await Swal.fire({title:"Novo fluxo",input:"text",inputPlaceholder:"Nome do fluxo",showCancelButton:true,background:"#080808",color:"#fff",confirmButtonColor:"#fff",inputValidator:v=>!v?.trim()?"Digite um nome":undefined}):{isConfirmed:true,value:"Novo fluxo"};if(res.isConfirmed){const f={id:uid(),name:res.value.trim(),createdAt:Date.now(),updatedAt:Date.now(),nodes:[],edges:[]};db.flows.unshift(f);doc=f;save("Fluxo criado");switchDoc(f.id)}}else if(a==="delete-flow"){if(db.flows.length===1)return notify("Mantenha pelo menos um fluxo","info");if(await confirmBox({title:"Excluir este fluxo?",text:"Esta ação não poderá ser desfeita.",icon:"warning",showCancelButton:true,confirmButtonText:"Excluir",cancelButtonText:"Cancelar"})){const deletedId=doc.id;db.flows=db.flows.filter(f=>f.id!==deletedId);doc=db.flows[0];persist();renderList();switchDoc(doc.id);if(cloud&&deletedId)try{await cloud.onDelete?.(deletedId)}catch(e){console.error("Flow delete sync:",e);notify("Fluxo removido localmente; exclusão na nuvem pendente","error")}notify("Fluxo excluído")}}else if(a==="undo"&&history.length){future.push(snapshot());restore(history.pop())}else if(a==="redo"&&future.length){history.push(snapshot());restore(future.pop())}else if(a==="zoom-in"){zoom=clamp(zoom*1.15,.35,2.5);draw()}else if(a==="zoom-out"){zoom=clamp(zoom/1.15,.35,2.5);draw()}else if(a==="zoom-reset"){zoom=1;pan={x:0,y:0};draw()}else if(a==="fit"){if(!doc.nodes.length){zoom=1;pan={x:0,y:0};draw();return}const minX=Math.min(...doc.nodes.map(n=>n.x)),minY=Math.min(...doc.nodes.map(n=>n.y)),maxX=Math.max(...doc.nodes.map(n=>n.x+n.w)),maxY=Math.max(...doc.nodes.map(n=>n.y+n.h)),r=stage.getBoundingClientRect();zoom=clamp(Math.min((r.width-80)/(maxX-minX),(r.height-80)/(maxY-minY)),.35,1.4);pan={x:(r.width-(maxX-minX)*zoom)/2-minX*zoom,y:(r.height-(maxY-minY)*zoom)/2-minY*zoom};draw()}else if(a==="export-json"){download(new Blob([JSON.stringify(doc,null,2)],{type:"application/json"}),doc.name.replace(/\W+/g,"-")+".json");notify("JSON exportado")}else if(a==="export-png"){const link=document.createElement("a");link.download=doc.name.replace(/\W+/g,"-")+".png";link.href=canvas.toDataURL("image/png");link.click();notify("PNG exportado")}else if(a==="import"){$("#flowImport").click()}}
 $$("[data-act]").forEach(b=>b.onclick=()=>action(b.dataset.act));$$("[data-mode]").forEach(b=>b.onclick=()=>{mode=b.dataset.mode;connectFrom=null;$$("[data-mode]").forEach(x=>x.classList.toggle("active",x===b))});
 $("#flowName").value=doc.name;$("#flowName").onchange=()=>{doc.name=$("#flowName").value.trim()||"Fluxo sem nome";save("Fluxo renomeado")};
 $("#flowImport").onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const x=JSON.parse(await file.text());if(!Array.isArray(x.nodes)||!Array.isArray(x.edges))throw 0;const f={id:uid(),name:x.name||file.name.replace(/\.json$/i,""),createdAt:Date.now(),updatedAt:Date.now(),nodes:x.nodes,edges:x.edges.map(y=>({...y,id:y.id||uid()}))};db.flows.unshift(f);doc=f;save("Fluxo importado");switchDoc(f.id)}catch{notify("Arquivo JSON inválido","error")}e.target.value=""};
 canvas.ondblclick=e=>{const p=world(e);addNode(p.x-95,p.y-41)};
 canvas.onpointerdown=e=>{canvas.setPointerCapture(e.pointerId);const p=world(e),n=hit(p);selectedEdge=null;if(mode==="node"){addNode(p.x-95,p.y-41);mode="select";return}if(mode==="delete"&&n){selected=n.id;removeSelected();return}if(mode==="connect"&&n){if(connectFrom&&connectFrom!==n.id){checkpoint();doc.edges.push({id:uid(),a:connectFrom,b:n.id});connectFrom=null;save("Conexão criada")}else connectFrom=n.id;selected=n.id;draw();renderProps();return}if(n){selected=n.id;checkpoint();drag={id:n.id,dx:p.x-n.x,dy:p.y-n.y};renderProps()}else{selected=null;drag={pan:true,x:e.clientX-pan.x,y:e.clientY-pan.y};renderProps()}draw()};
 canvas.onpointermove=e=>{if(!drag)return;if(drag.pan){pan.x=e.clientX-drag.x;pan.y=e.clientY-drag.y}else{const p=world(e),n=doc.nodes.find(x=>x.id===drag.id);if(n){n.x=p.x-drag.dx;n.y=p.y-drag.dy}}draw()};
 canvas.onpointerup=()=>{if(drag&&!drag.pan)save();drag=null};canvas.onwheel=e=>{e.preventDefault();zoom=clamp(zoom*(e.deltaY<0?1.08:.92),.35,2.5);draw()};
 const keydown=e=>{if(!root.isConnected)return;if(["INPUT","TEXTAREA","SELECT"].includes(document.activeElement.tagName))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="z"){e.preventDefault();action(e.shiftKey?"redo":"undo");return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="d"&&selected){e.preventDefault();const n=doc.nodes.find(x=>x.id===selected);if(n){checkpoint();const cp={...n,id:uid(),x:n.x+30,y:n.y+30};doc.nodes.push(cp);selected=cp.id;save("Bloco duplicado");draw();renderProps()}return}if(e.key==="Delete"||e.key==="Backspace")removeSelected();if(e.key.toLowerCase()==="v")mode="select";if(e.key.toLowerCase()==="n")mode="node";if(e.key.toLowerCase()==="c")mode="connect"};window.addEventListener("keydown",keydown);
 new ResizeObserver(resize).observe(stage);renderList();renderProps();resize();persist();
}