import{extractWikilinks,wikilinkQuery,replaceWikilinkTitle}from"./wikilinks.js";
import{renderMarkdown}from"./markdown.js";
import{NOTE_TYPES,defaultProperties,templateFor,propertyFields}from"./note-templates.js";
import{mountKnowledgeGraph}from"./knowledge-graph.js";
const esc=s=>{const d=document.createElement("div");d.textContent=s??"";return d.innerHTML};
export function secondBrainView(notes=[]){const types=Object.entries(NOTE_TYPES).map(([k,v])=>'<option value="'+k+'">'+v.label+'</option>').join("");return '<section class="brain-shell"><div class="brain-head"><div><span class="eyebrow">Segundo Cérebro</span><h1>Knowledge Base</h1><p>Markdown, wikilinks, backlinks e grafo de conhecimento.</p></div><button class="primary" id="brainNew">＋ Nova nota</button></div><div class="brain-tabs"><button class="active" data-brain-tab="notes">Notas</button><button data-brain-tab="graph">Grafo</button></div><div id="brainNotes"><div class="brain-toolbar"><div class="tool-search-wrap">⌕<input id="brainSearch" class="search" placeholder="Buscar título, conteúdo ou tag..."></div><select id="brainType"><option value="">Todos os tipos</option>'+types+'</select><select id="brainTag"><option value="">Todas as tags</option>'+[...new Set(notes.flatMap(n=>n.tags||[]))].sort().map(t=>'<option value="'+esc(t)+'">#'+esc(t)+'</option>').join("")+'</select></div><div class="brain-list" id="brainList"></div></div><div id="brainGraphPanel" hidden><div class="brain-toolbar"><div class="tool-search-wrap">⌕<input id="graphSearch" class="search" placeholder="Filtrar nós..."></div><select id="graphType"><option value="">Todos os tipos</option>'+types+'</select><select id="graphTag"><option value="">Todas as tags</option>'+[...new Set(notes.flatMap(n=>n.tags||[]))].sort().map(t=>'<option value="'+esc(t)+'">#'+esc(t)+'</option>').join("")+'</select><button id="graphGlobal" class="ghost-action">Grafo global</button></div><div id="knowledgeGraph" class="knowledge-graph"></div></div><div id="brainEditorHost"></div></section>'}
export function mountSecondBrain(root,{notes,onSave,onDelete,onSyncLinks,getBacklinks,getGraph,makeId,notify}){
 let active=null,graphDispose=null,graphData={nodes:[],links:[]};const $=s=>root.querySelector(s),$$=s=>[...root.querySelectorAll(s)];
 const typeLabel=t=>NOTE_TYPES[t]?.label||NOTE_TYPES.concept.label;
 const paintList=()=>{const q=($("#brainSearch")?.value||"").toLocaleLowerCase(),type=$("#brainType")?.value||"",tag=$("#brainTag")?.value||"";const list=notes.filter(n=>(!type||(n.type||"concept")===type)&&(!tag||(n.tags||[]).includes(tag))&&(!q||(n.title+" "+n.body+" "+(n.tags||[]).join(" ")).toLocaleLowerCase().includes(q)));$("#brainList").innerHTML=list.length?list.map(n=>'<article class="brain-note" data-brain-open="'+n.id+'"><div><span class="brain-type">'+(NOTE_TYPES[n.type||"concept"]?.icon||"◇")+' '+typeLabel(n.type)+'</span><h3>'+esc(n.title||"Sem título")+'</h3><p>'+esc((n.body||"").replace(/[#*]/g,"").slice(0,150))+'</p></div><div class="brain-note-meta"><span>'+((n.tags||[]).slice(0,3).map(t=>"#"+esc(t)).join(" ")||"sem tags")+'</span><small>'+new Date(n.updatedAt||n.createdAt).toLocaleDateString("pt-BR")+'</small></div></article>').join(""):'<div class="tools-empty"><strong>Nenhuma nota encontrada</strong><p>Crie ou ajuste os filtros.</p></div>';$$("[data-brain-open]").forEach(b=>b.onclick=()=>openEditor(notes.find(n=>n.id===b.dataset.brainOpen)))};
 async function openEditor(note=null){let fresh=!note;const now=Date.now(),tpl=templateFor("concept");active=note||{id:makeId(),title:"",body:tpl.body,tags:[],type:"concept",properties:tpl.properties,pinned:false,favorite:false,createdAt:now,updatedAt:now};const host=$("#brainEditorHost");host.innerHTML='<div class="brain-editor-overlay"><div class="brain-editor"><header><button id="brainClose">← Voltar</button><div><button class="ghost-action" id="brainLocalGraph">Grafo local</button><small id="brainSaveState">'+(fresh?"Nova nota":"Salva")+'</small><button class="primary" id="brainSave">Salvar</button></div></header><div class="brain-editor-grid"><aside class="brain-props"><label>Título<input id="brainTitle" maxlength="120" value="'+esc(active.title)+'"></label><label>Tipo<select id="brainEditType">'+Object.entries(NOTE_TYPES).map(([k,v])=>'<option value="'+k+'" '+((active.type||"concept")===k?"selected":"")+'>'+v.label+'</option>').join("")+'</select></label><label>Tags<input id="brainTags" value="'+esc((active.tags||[]).join(", "))+'" placeholder="ideia, projeto"></label><div id="brainExtraProps" class="brain-extra">'+propertyFields(active.type||"concept",active.properties||{})+'</div><div class="brain-backlinks"><strong>Citada por</strong><div id="brainBacklinks">Carregando…</div></div>'+(fresh?"":'<button class="danger" id="brainDelete">Excluir nota</button>')+'</aside><main class="brain-writing"><div class="brain-editor-tabs"><button class="active" data-edit-tab="write">Markdown</button><button data-edit-tab="preview">Pré-visualização</button></div><div class="brain-text-wrap"><textarea id="brainBody" spellcheck="true" placeholder="Escreva em Markdown. Use [[Nome da nota]] para criar conexões.">'+esc(active.body||"")+'</textarea><div id="wikiSuggest" class="wiki-suggest" hidden></div></div><article id="brainPreview" class="markdown-preview" hidden></article></main></div></div></div>';
 const title=$("#brainTitle"),body=$("#brainBody"),type=$("#brainEditType"),extra=$("#brainExtraProps"),preview=$("#brainPreview"),suggest=$("#wikiSuggest");
 const renderPreview=()=>{let html=renderMarkdown(body.value,notes);const props=collectProps();if(type.value==="moc"){const linked=notes.filter(n=>(!props.autoType||n.type===props.autoType)&&(!props.autoTag||(n.tags||[]).includes(props.autoTag))&&n.id!==active.id);if(linked.length)html+='<section class="moc-auto"><h2>Notas relacionadas</h2>'+linked.map(n=>'<button data-note-id="'+n.id+'" class="md-wikilink">'+esc(n.title)+'</button>').join("")+'</section>'}preview.innerHTML=html;preview.querySelectorAll("[data-note-id]").forEach(b=>b.onclick=()=>openEditor(notes.find(n=>n.id===b.dataset.noteId)))};
 const collectProps=()=>Object.fromEntries($$("[data-prop]").map(x=>[x.dataset.prop,x.value]));
 type.onchange=()=>{const tpl=templateFor(type.value);extra.innerHTML=propertyFields(type.value,active.type===type.value?active.properties:tpl.properties);if(fresh&&!body.value.trim())body.value=tpl.body;renderPreview()};
 $$("[data-edit-tab]").forEach(b=>b.onclick=()=>{$$("[data-edit-tab]").forEach(x=>x.classList.toggle("active",x===b));const show=b.dataset.editTab==="preview";body.hidden=show;preview.hidden=!show;if(show)renderPreview()});
 body.addEventListener("input",()=>{const w=wikilinkQuery(body.value,body.selectionStart);if(!w){suggest.hidden=true;return}const q=w.query.toLocaleLowerCase(),matches=notes.filter(n=>n.id!==active.id&&(n.title||"").toLocaleLowerCase().includes(q)).slice(0,7);suggest.hidden=false;suggest.innerHTML=matches.map(n=>'<button data-wiki-pick="'+n.id+'">'+esc(n.title)+'</button>').join("")+'<button data-wiki-create="'+esc(w.query)+'">＋ Criar “'+esc(w.query||"nova nota")+'”</button>';suggest.querySelectorAll("[data-wiki-pick]").forEach(b=>b.onclick=()=>{const n=notes.find(x=>x.id===b.dataset.wikiPick),end=body.selectionStart;body.value=body.value.slice(0,w.start)+"[["+n.title+"]]"+body.value.slice(end);body.focus();body.selectionStart=body.selectionEnd=w.start+n.title.length+4;suggest.hidden=true});suggest.querySelector("[data-wiki-create]")?.addEventListener("click",async()=>{const name=(w.query||"Nova nota").trim(),n={id:makeId(),title:name,body:"",tags:[],type:"concept",properties:{},pinned:false,favorite:false,createdAt:Date.now(),updatedAt:Date.now()};notes.unshift(n);await onSave(n);const end=body.selectionStart;body.value=body.value.slice(0,w.start)+"[["+name+"]]"+body.value.slice(end);suggest.hidden=true;notify?.("Nota conectada criada")})});
 async function loadBacklinks(){if(fresh){$("#brainBacklinks").innerHTML='<span class="brain-muted">Salve a nota para gerar backlinks.</span>';return}try{const rows=await getBacklinks(active.id);$("#brainBacklinks").innerHTML=rows.length?rows.map(n=>'<button data-backlink="'+n.id+'">'+esc(n.title)+'</button>').join(""):'<span class="brain-muted">Nenhuma nota aponta para esta.</span>';$$("[data-backlink]").forEach(b=>b.onclick=()=>openEditor(notes.find(n=>n.id===b.dataset.backlink)))}catch{$("#brainBacklinks").textContent="Backlinks indisponíveis"}}
 await loadBacklinks();
 $("#brainClose").onclick=()=>{host.innerHTML="";active=null;paintList()};$("#brainLocalGraph").onclick=async()=>{const id=active.id;host.innerHTML="";active=null;const tab=$('[data-brain-tab="graph"]');tab?.click();await loadGraph(id)};
 $("#brainSave").onclick=async()=>{const oldTitle=active.title;active.title=title.value.trim()||"Sem título";active.body=body.value;active.type=type.value;active.tags=[...new Set($("#brainTags").value.split(",").map(x=>x.trim().toLocaleLowerCase()).filter(Boolean))].slice(0,20);active.properties=collectProps();active.updatedAt=Date.now();$("#brainSaveState").textContent="Salvando…";if(fresh&&!notes.some(n=>n.id===active.id))notes.unshift(active);if(oldTitle&&oldTitle!==active.title){for(const n of notes){if(n.id===active.id)continue;const changed=replaceWikilinkTitle(n.body||"",oldTitle,active.title);if(changed!==n.body){n.body=changed;n.updatedAt=Date.now();await onSave(n)}}}await onSave(active);await onSyncLinks(active,extractWikilinks(active.body));fresh=false;$("#brainSaveState").textContent="Salva na nuvem";notify?.("Nota salva e conexões atualizadas");paintList();await loadBacklinks()};
 $("#brainDelete")?.addEventListener("click",async()=>{if(confirm("Excluir esta nota e suas conexões?")){await onDelete(active);const i=notes.findIndex(n=>n.id===active.id);if(i>=0)notes.splice(i,1);host.innerHTML="";active=null;paintList();notify?.("Nota excluída")}});
 }
 async function loadGraph(localId=null){graphDispose?.();graphData=await getGraph();let nodes=graphData.nodes,links=graphData.links;const q=($("#graphSearch")?.value||"").toLocaleLowerCase(),type=$("#graphType")?.value||"",tag=$("#graphTag")?.value||"";if(localId){const ids=new Set([localId]);links.forEach(l=>{if(l.source===localId)ids.add(l.target);if(l.target===localId)ids.add(l.source)});nodes=nodes.filter(n=>ids.has(n.id));links=links.filter(l=>ids.has(l.source)&&ids.has(l.target))}nodes=nodes.filter(n=>(!q||n.title.toLocaleLowerCase().includes(q))&&(!type||n.type===type)&&(!tag||(n.tags||[]).includes(tag)));const ids=new Set(nodes.map(n=>n.id));links=links.filter(l=>ids.has(l.source)&&ids.has(l.target));graphDispose=await mountKnowledgeGraph($("#knowledgeGraph"),{nodes,links,localId,onOpen:id=>openEditor(notes.find(n=>n.id===id))})}
 $("#brainNew").onclick=()=>openEditor();["brainSearch","brainType","brainTag"].forEach(id=>$("#"+id)?.addEventListener(id==="brainSearch"?"input":"change",paintList));$$("[data-brain-tab]").forEach(b=>b.onclick=async()=>{$$("[data-brain-tab]").forEach(x=>x.classList.toggle("active",x===b));const graph=b.dataset.brainTab==="graph";$("#brainNotes").hidden=graph;$("#brainGraphPanel").hidden=!graph;if(graph)await loadGraph()});["graphSearch","graphType","graphTag"].forEach(id=>$("#"+id)?.addEventListener(id==="graphSearch"?"input":"change",()=>loadGraph()));$("#graphGlobal").onclick=()=>loadGraph();paintList();return{openEditor,openLocalGraph:async id=>{const tab=$('[data-brain-tab="graph"]');tab?.click();await loadGraph(id)},destroy:()=>graphDispose?.()}}
