import{listVaultItems,saveVaultItem,deleteVaultItem,logVaultAccess}from"../services/neon.js?v=5.22.0";
const te=new TextEncoder(),td=new TextDecoder(),b64=b=>btoa(String.fromCharCode(...new Uint8Array(b))),unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function key(password,salt,iterations){const base=await crypto.subtle.importKey("raw",te.encode(password),"PBKDF2",false,["deriveKey"]);return crypto.subtle.deriveKey({name:"PBKDF2",hash:"SHA-256",salt,iterations},base,{name:"AES-GCM",length:256},false,["encrypt","decrypt"])}
export async function encryptVault(payload,password){const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),iterations=310000,k=await key(password,salt,iterations),cipher=await crypto.subtle.encrypt({name:"AES-GCM",iv},k,te.encode(JSON.stringify(payload)));return{ciphertext:b64(cipher),iv:b64(iv),salt:b64(salt),iterations}}
export async function decryptVault(row,password){const k=await key(password,unb64(row.salt),row.kdf_iterations||310000),plain=await crypto.subtle.decrypt({name:"AES-GCM",iv:unb64(row.iv)},k,unb64(row.ciphertext));return JSON.parse(td.decode(plain))}
let master=null,lastActivity=0,timer=null;const LOCK_MS=5*60*1000;
function touch(){lastActivity=Date.now();clearTimeout(timer);timer=setTimeout(lockVault,LOCK_MS)}
export function lockVault(){master=null;lastActivity=0;clearTimeout(timer);timer=null;window.dispatchEvent(new CustomEvent("td:vault-locked"))}
async function askPassword(confirm=false){const r=await Swal.fire({title:confirm?"Criar senha mestra":"Desbloquear cofre",text:confirm?"A senha não pode ser recuperada. Se perdê-la, os dados serão perdidos.":"Digite sua senha mestra. Ela nunca é enviada ao servidor.",input:"password",inputAttributes:{autocomplete:"new-password"},showCancelButton:true,confirmButtonText:confirm?"Continuar":"Desbloquear",cancelButtonText:"Cancelar",background:"#080808",color:"#fff",preConfirm:v=>v?.length>=8?v:Swal.showValidationMessage("Use pelo menos 8 caracteres")});return r.isConfirmed?r.value:null}
async function unlock(){if(master&&Date.now()-lastActivity<LOCK_MS){touch();return master}master=await askPassword(false);if(master)touch();return master}
export async function vaultDialog(notify){
 const rows=await listVaultItems();const r=await Swal.fire({title:"Cofre de credenciais",html:`<div class="vault-warning">AES-256-GCM no dispositivo · auto-lock em 5 min.<br>Perdeu a senha mestra = perdeu os dados criptografados.</div><div class="ops-modal-list">${rows.map((x,i)=>`<button data-vault-open="${x.id}"><b>Credencial ${i+1}</b><small>${new Date(x.updated_at).toLocaleString("pt-BR")}</small></button>`).join("")||"<p>Cofre vazio.</p>"}</div>`,showCancelButton:true,confirmButtonText:"Nova credencial",cancelButtonText:"Fechar",background:"#080808",color:"#fff",didOpen:()=>document.querySelectorAll("[data-vault-open]").forEach(b=>b.onclick=async()=>{Swal.close();await openItem(rows.find(x=>x.id===b.dataset.vaultOpen),notify)})});if(r.isConfirmed)await createItem(notify)
}
async function createItem(notify){const pass=master||await askPassword(true);if(!pass)return;master=pass;touch();const r=await Swal.fire({title:"Nova credencial",html:'<div class="ops-form"><input id="vTitle" placeholder="Nome / sistema"><input id="vUser" placeholder="Usuário / e-mail"><input id="vPass" type="password" placeholder="Senha / segredo"><input id="vUrl" placeholder="URL (opcional)"><textarea id="vNotes" placeholder="Notas"></textarea></div>',showCancelButton:true,confirmButtonText:"Criptografar e salvar",cancelButtonText:"Cancelar",background:"#080808",color:"#fff",preConfirm:()=>({title:document.querySelector("#vTitle").value,username:document.querySelector("#vUser").value,password:document.querySelector("#vPass").value,url:document.querySelector("#vUrl").value,notes:document.querySelector("#vNotes").value})});if(r.isConfirmed){const encrypted=await encryptVault(r.value,pass);const saved=await saveVaultItem(encrypted);await logVaultAccess(saved.id,"create");notify("Credencial criptografada e salva")}}
async function openItem(row,notify){const pass=await unlock();if(!pass)return;try{const data=await decryptVault(row,pass);await logVaultAccess(row.id,"decrypt");const r=await Swal.fire({title:data.title||"Credencial",html:`<div class="vault-detail"><label>Usuário</label><code>${data.username||"—"}</code><label>Senha / segredo</label><code>••••••••</code>${data.url?`<label>URL</label><code>${data.url}</code>`:""}${data.notes?`<label>Notas</label><p>${data.notes}</p>`:""}</div>`,showDenyButton:true,showCancelButton:true,confirmButtonText:"Copiar senha",denyButtonText:"Excluir",cancelButtonText:"Fechar",background:"#080808",color:"#fff"});if(r.isConfirmed){await navigator.clipboard.writeText(data.password||"");await logVaultAccess(row.id,"copy_secret");notify("Copiado. Clipboard será limpo em 30 segundos");setTimeout(()=>navigator.clipboard.writeText("").catch(()=>{}),30000)}if(r.isDenied){await deleteVaultItem(row.id);await logVaultAccess(row.id,"delete");notify("Credencial removida")}}catch{lockVault();notify("Senha mestra inválida ou conteúdo corrompido","error")}}
["pointerdown","keydown","touchstart"].forEach(e=>window.addEventListener(e,()=>{if(master)touch()},{passive:true}));
