import{getTools,getKnowledgeIndex,refreshToolCockpit}from"./tools-cockpit.js?v=5.26.0";
import{getToolKnowledgeEntry,searchToolKnowledge,saveToolKnowledgeEntry,deleteToolKnowledgeEntry}from"../services/neon.js?v=5.26.0";
import{renderMarkdown}from"./markdown.js?v=5.26.0";
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const toolName=id=>getTools().find(t=>t.id===id)?.name||"Geral";
const options=id=>'<option value="">Sem ferramenta</option>'+getTools().map(t=>`<option value="${esc(t.id)}" ${id===t.id?"selected":""}>${esc(t.name)}</option>`).join("");
function viewerHtml(row){return `<div class="kb-view"><div class="kb-meta"><span>${esc(toolName(row.tool_id))}</span>${row.error_code?`<code>${esc(row.error_code)}</code>`:""}${(row.tags||[]).map(x=>`<span>#${esc(x)}</span>`).join("")}</div><article class="kb-markdown">${renderMarkdown(row.body||"")}</article></div>`}
export async function openKnowledgeEntry(id,notify=()=>{}){const row=await getToolKnowledgeEntry(id);if(!row){notify("Entrada não encontrada","error");return}const r=await Swal.fire({title:row.title||"Conhecimento",width:900,html:viewerHtml(row),showCancelButton:true,showDenyButton:true,confirmButtonText:"Editar",denyButtonText:"Excluir",cancelButtonText:"Fechar",background:"#080808",color:"#fff"});if(r.isConfirmed)await knowledgeEditor(row,notify);if(r.isDenied){const ok=await Swal.fire({title:"Excluir entrada?",text:"Esta ação remove a entrada da Base de Conhecimento.",icon:"warning",showCancelButton:true,confirmButtonText:"Excluir",cancelButtonText:"Cancelar",background:"#080808",color:"#fff"});if(ok.isConfirmed){await deleteToolKnowledgeEntry(row.id);await refreshToolCockpit({full:true});notify("Entrada removida")}}}
export async function knowledgeEditor(row=null,notify=()=>{}){const r=await Swal.fire({title:row?"Editar conhecimento":"Nova entrada",width:980,html:`<div class="kb-editor"><div class="ops-form"><select id="kbTool">${options(row?.tool_id)}</select><input id="kbTitle" placeholder="Título" value="${esc(row?.title||"")}"><div class="os-cols"><input id="kbError" placeholder="Código de erro" value="${esc(row?.error_code||"")}"><input id="kbTags" placeholder="Tags separadas por vírgula" value="${esc((row?.tags||[]).join(", "))}"></div><textarea id="kbBody" placeholder="# Solução&#10;&#10;Descreva diagnóstico, comandos e resolução...">${esc(row?.body||"")}</textarea></div><div class="kb-preview"><small>PREVIEW MARKDOWN</small><article id="kbPreview" class="kb-markdown"></article></div></div>`,showCancelButton:true,confirmButtonText:"Salvar",cancelButtonText:"Cancelar",background:"#080808",color:"#fff",didOpen:()=>{const input=document.querySelector("#kbBody"),preview=document.querySelector("#kbPreview"),paint=()=>preview.innerHTML=renderMarkdown(input.value||"");input.addEventListener("input",paint);paint()},preConfirm:()=>{const title=document.querySelector("#kbTitle").value.trim();if(!title)return Swal.showValidationMessage("Informe um título");return{id:row?.id,toolId:document.querySelector("#kbTool").value||null,title,body:document.querySelector("#kbBody").value,errorCode:document.querySelector("#kbError").value,tags:document.querySelector("#kbTags").value.split(",")}}});if(r.isConfirmed){const saved=await saveToolKnowledgeEntry(r.value);await refreshToolCockpit({full:true});notify("Conhecimento salvo");return saved}}
export async function knowledgeBaseDialog(notify=()=>{},initialQuery=""){let query=initialQuery,rows=query?await searchToolKnowledge(query):getKnowledgeIndex();const show=async()=>{const r=await Swal.fire({title:"Base de Conhecimento 2.0",width:920,html:`<div class="kb-search"><input id="kbSearch" placeholder="Buscar solução, erro, comando ou tag..." value="${esc(query)}"><button id="kbSearchBtn">Buscar</button></div><div class="ops-modal-list kb-results">${rows.map(x=>`<button data-kb-open="${x.id}"><b>${esc(x.title)}</b><small>${esc(toolName(x.tool_id))}${x.error_code?" · "+esc(x.error_code):""}${x.tags?.length?" · #"+x.tags.map(esc).join(" #"):""}</small></button>`).join("")||"<p>Nenhum conhecimento encontrado.</p>"}</div>`,showCancelButton:true,confirmButtonText:"Nova entrada",cancelButtonText:"Fechar",background:"#080808",color:"#fff",didOpen:()=>{const run=async()=>{query=document.querySelector("#kbSearch").value.trim();rows=query?await searchToolKnowledge(query):getKnowledgeIndex();Swal.close();await show()};document.querySelector("#kbSearchBtn").onclick=run;document.querySelector("#kbSearch").onkeydown=e=>{if(e.key==="Enter"){e.preventDefault();run()}};document.querySelectorAll("[data-kb-open]").forEach(b=>b.onclick=async()=>{Swal.close();await openKnowledgeEntry(b.dataset.kbOpen,notify)})}});if(r.isConfirmed){await knowledgeEditor(null,notify);rows=query?await searchToolKnowledge(query):getKnowledgeIndex();await show()}};await show()}
window.addEventListener("td:open-kb",e=>{const id=e.detail?.id,query=e.detail?.query;if(id)openKnowledgeEntry(id);else knowledgeBaseDialog(()=>{},query||"")});
