import{tools as fallbackTools}from"../data/tools.js?v=5.30.0";
import{listToolCockpitSnapshot}from"../services/neon.js?v=5.30.0";
const CACHE_PREFIX="td:tools:cockpit:v3:",CACHE_VERSION=3,FULL_SYNC_MS=5*60*1000;
const labels={"ia":"IA","automacao":"Automação","produtividade":"Produtividade","marketing":"Marketing","design-documentacao":"Design & Documentação","seguranca":"Segurança","educacao":"Educação","utilidades":"Utilidades","vendas-crm":"Vendas & CRM","dev-infra-cloud":"Dev & Infra Cloud","suporte-remoto-help-desk":"Suporte Remoto & Help Desk","diagnostico-so":"Diagnóstico & SO"};
const mapTool=t=>({id:t.id,name:t.name,description:t.description||"",category:labels[t.tool_categories?.slug]||t.tool_categories?.name||"Utilidades",categorySlug:t.tool_categories?.slug||"utilidades",url:t.launch_url||"",launchUrl:t.launch_url||"",loginUrl:t.login_url||"",icon:t.icon||String(t.name||"?").slice(0,2).toUpperCase(),kind:t.kind||"catalog",saasCost:t.saas_cost==null?null:Number(t.saas_cost),currency:t.currency||null,billingCycle:t.billing_cycle||"none",updatedAt:t.updated_at||null,tags:(t.tool_tag_links||[]).map(x=>x.tool_tags).filter(Boolean)});
const fallback=fallbackTools.map(t=>({...t,launchUrl:t.url,loginUrl:null,kind:"catalog",tags:[],saasCost:null,currency:null,billingCycle:"none"}));
export const toolCockpit={userId:null,tools:fallback,stacks:[],quickLinks:[],checklists:[],knowledge:[],updatedAt:null,lastFullSync:0,ready:false};
const key=id=>CACHE_PREFIX+id,read=id=>{try{const x=JSON.parse(localStorage.getItem(key(id))||"null");return x?.version===CACHE_VERSION&&x.userId===id?x:null}catch{return null}},write=data=>{if(!toolCockpit.userId)return;try{localStorage.setItem(key(toolCockpit.userId),JSON.stringify({version:CACHE_VERSION,userId:toolCockpit.userId,savedAt:Date.now(),...data}))}catch{}};
function reset(userId=null){toolCockpit.userId=userId;toolCockpit.tools=fallback;toolCockpit.stacks=[];toolCockpit.quickLinks=[];toolCockpit.checklists=[];toolCockpit.knowledge=[];toolCockpit.updatedAt=null;toolCockpit.lastFullSync=0;toolCockpit.ready=false}
function hydrateUser(userId){if(!userId)return;if(toolCockpit.userId!==userId)reset(userId);const cached=read(userId);if(cached&&!toolCockpit.ready){toolCockpit.tools=cached.tools?.length?cached.tools:fallback;toolCockpit.stacks=cached.stacks||[];toolCockpit.quickLinks=cached.quickLinks||[];toolCockpit.checklists=cached.checklists||[];toolCockpit.knowledge=cached.knowledge||[];toolCockpit.updatedAt=cached.updatedAt||null;toolCockpit.lastFullSync=cached.lastFullSync||0}}
export function clearToolCockpit(){reset();window.dispatchEvent(new CustomEvent("td:tools-refreshed"))}
export const getTools=()=>toolCockpit.tools;export const getStacks=()=>toolCockpit.stacks;export const getQuickLinks=()=>toolCockpit.quickLinks;export const getChecklists=()=>toolCockpit.checklists;export const getKnowledgeIndex=()=>toolCockpit.knowledge;export const findTool=id=>toolCockpit.tools.find(x=>x.id===id);
export function monthlySaasTotals(){const totals={};for(const t of toolCockpit.tools){if(t.saasCost==null||!t.currency||t.billingCycle==="none")continue;const v=t.billingCycle==="annual"?t.saasCost/12:t.saasCost;totals[t.currency]=(totals[t.currency]||0)+v}return totals}
export function localToolSearch(query){const q=(query||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim();if(!q)return toolCockpit.tools;const tokens=q.split(/\s+/).filter(Boolean);return toolCockpit.tools.map(t=>{const tags=(t.tags||[]).map(x=>x.slug||x.name||"").join(" ");const hay=(t.name+" "+t.description+" "+t.category+" "+tags).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase();let score=0;for(const token of tokens){if(t.name.toLowerCase().includes(token))score+=8;if(tags.includes(token))score+=6;if(t.category.toLowerCase().includes(token))score+=3;if(hay.includes(token))score+=1}return{t,score}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).map(x=>x.t)}
export async function refreshToolCockpit(options={}){const forceFull=!!options.full||!toolCockpit.lastFullSync||Date.now()-toolCockpit.lastFullSync>FULL_SYNC_MS,data=await listToolCockpitSnapshot(forceFull?null:toolCockpit.updatedAt);if(!data)return toolCockpit;hydrateUser(data.userId);const full=forceFull||toolCockpit.userId!==data.userId,merge=(a,b)=>{const m=new Map((a||[]).map(x=>[x.id,x]));for(const x of b||[])m.set(x.id,x);return[...m.values()]};toolCockpit.tools=full?(data.tools||[]).map(mapTool):merge(toolCockpit.tools,(data.tools||[]).map(mapTool));toolCockpit.stacks=full?(data.stacks||[]):merge(toolCockpit.stacks,data.stacks||[]);toolCockpit.quickLinks=full?(data.quickLinks||[]):merge(toolCockpit.quickLinks,data.quickLinks||[]);toolCockpit.checklists=full?(data.checklists||[]):merge(toolCockpit.checklists,data.checklists||[]);toolCockpit.knowledge=full?(data.knowledge||[]):merge(toolCockpit.knowledge,data.knowledge||[]);toolCockpit.updatedAt=data.serverTime||new Date().toISOString();if(full)toolCockpit.lastFullSync=Date.now();toolCockpit.ready=true;write({tools:toolCockpit.tools,stacks:toolCockpit.stacks,quickLinks:toolCockpit.quickLinks,checklists:toolCockpit.checklists,knowledge:toolCockpit.knowledge,updatedAt:toolCockpit.updatedAt,lastFullSync:toolCockpit.lastFullSync});window.dispatchEvent(new CustomEvent("td:tools-refreshed"));return toolCockpit}
