import{tools}from"./data/tools.js";
import{mountFlow}from"./modules/flow-tools.js";
const $=s=>document.querySelector(s),store={get:(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set:(k,v)=>localStorage.setItem(k,JSON.stringify(v))};
let view="dashboard",category="Todos";
const projects=[
{name:"Diamond Game",status:"Em desenvolvimento",description:"Plataforma 1x1 competitiva",links:[["Frontend","https://github.com/CarlosDevITT/Diamond-Game"],["Servidor","https://github.com/CarlosDevITT/Diamond-Game-Server"],["Appwrite","https://cloud.appwrite.io"],["Railway","https://railway.com"]]},
{name:"Ignite Restaurante",status:"Operacional",description:"Cardápio digital, PDV e PWA",links:[["Vercel","https://ignite-restaurant-kappa.vercel.app"],["Supabase","https://supabase.com/dashboard"]]},
{name:"States Service",status:"Em desenvolvimento",description:"Ecossistema de serviços States Softwares",links:[["GitHub","https://github.com/CarlosDevITT/States-All"],["Supabase","https://supabase.com/dashboard"]]}
];
const state={favorites:new Set(store.get("td:favorites",[])),recent:store.get("td:recent",[]),usage:store.get("td:usage",{}),notes:store.get("td:notes",[]),transactions:store.get("td:transactions",[])};
const esc=s=>{const d=document.createElement("div");d.textContent=s??"";return d.innerHTML};
function toolCard(t){const uses=state.usage[t.id]||0;return `<article class="card tool-card" data-open="${t.id}" tabindex="0" role="button" aria-label="Abrir ${esc(t.name)}"><button class="fav ${state.favorites.has(t.id)?"on":""}" data-fav="${t.id}" aria-label="Favoritar">★</button><div class="tool-icon">${esc(t.icon)}</div><span class="tool-category">${esc(t.category)}</span><h3>${esc(t.name)}</h3><p>${esc(t.description)}</p><small class="tool-usage">${uses?`${uses} ${uses===1?"acesso":"acessos"}`:"Ainda não usado"} · Abrir ↗</small></article>`}
function openTool(id){const t=tools.find(x=>x.id===id);if(!t)return;state.recent=[id,...state.recent.filter(x=>x!==id)].slice(0,12);state.usage[id]=(state.usage[id]||0)+1;store.set("td:recent",state.recent);store.set("td:usage",state.usage);window.open(t.url,"_blank","noopener,noreferrer")}
function dashboard(){const fav=tools.filter(t=>state.favorites.has(t.id)),recent=state.recent.map(id=>tools.find(t=>t.id===id)).filter(Boolean),notes=state.notes.slice(0,3),inc=state.transactions.filter(x=>x.amount>0).reduce((a,b)=>a+b.amount,0),out=state.transactions.filter(x=>x.amount<0).reduce((a,b)=>a+b.amount,0),hour=new Date().getHours(),greeting=hour<12?"Bom dia":hour<18?"Boa tarde":"Boa noite";return `<div class="home-head"><div><span class="eyebrow">Workspace operacional</span><h1>${greeting}. O que vamos construir?</h1><p>Seu trabalho, projetos e ferramentas em um só lugar.</p></div><button class="home-search" data-action="command">⌕ Buscar <kbd>Ctrl K</kbd></button></div><div class="home-stats"><button data-go="tools"><span>Ferramentas</span><strong>${tools.length}</strong><small>${fav.length} favoritas</small></button><button data-go="projects"><span>Projetos</span><strong>${projects.length}</strong><small>workspaces ativos</small></button><button data-go="notes"><span>Notas</span><strong>${state.notes.length}</strong><small>salvas localmente</small></button><button data-go="finance"><span>Saldo local</span><strong>${money(inc+out)}</strong><small>${state.transactions.length} movimentações</small></button></div><div class="quick-actions"><button data-go="notes">＋ <span><strong>Nova nota</strong><small>Registrar uma ideia</small></span></button><button data-go="flow">⌁ <span><strong>Novo fluxo</strong><small>Abrir whiteboard</small></span></button><button data-go="qrcode">▦ <span><strong>Gerar QR</strong><small>Criar QR Code</small></span></button><button data-go="tools">◫ <span><strong>Explorar tools</strong><small>Abrir biblioteca</small></span></button></div><div class="home-columns"><section><div class="section-head"><h2>Projetos</h2><button data-go="projects">Ver todos</button></div><div class="home-projects">${projects.map(p=>`<button data-go="projects"><i>${esc(p.name.slice(0,2).toUpperCase())}</i><span><strong>${esc(p.name)}</strong><small>${esc(p.status)}</small></span><b>→</b></button>`).join("")}</div></section><section><div class="section-head"><h2>Notas recentes</h2><button data-go="notes">Abrir notas</button></div><div class="home-notes">${notes.length?notes.map(n=>`<button data-go="notes"><strong>${esc(n.title||"Sem título")}</strong><span>${esc((n.body||"").slice(0,80))}</span></button>`).join(""):`<div class="home-empty">Nenhuma nota ainda.<button data-go="notes">Criar primeira nota</button></div>`}</div></section></div><div class="section-head"><h2>Acesso recente</h2><button data-go="tools">Biblioteca</button></div><div class="grid">${(recent.length?recent:fav.length?fav:tools.slice(0,4)).slice(0,4).map(toolCard).join("")}</div>`}
function toolsView(){const cats=["Todos","Favoritos","Recentes","Mais usados",...new Set(tools.map(t=>t.category))],list=filteredTools("");return `<div class="tools-head"><div class="hero"><span class="eyebrow">Biblioteca operacional</span><h1>Ferramentas</h1><p>${tools.length} ferramentas centralizadas. Pesquise, favorite e deixe o sistema aprender quais você mais usa.</p></div><div class="tools-metrics"><span><strong>${state.favorites.size}</strong> favoritas</span><span><strong>${state.recent.length}</strong> recentes</span></div></div><div class="tool-search-wrap">⌕<input class="search" id="toolSearch" placeholder="Pesquisar por nome, categoria ou função..." autocomplete="off"></div><div class="filters">${cats.map(c=>`<button class="chip ${c===category?"active":""}" data-cat="${c}">${c}</button>`).join("")}</div><div class="tool-result-head"><span id="toolCount">${list.length} resultados</span><button id="clearToolFilters">Limpar filtros</button></div><div class="grid tools-grid" id="toolGrid">${list.map(toolCard).join("")}</div><div class="tools-empty" id="toolsEmpty" ${list.length?"hidden":""}>Nenhuma ferramenta encontrada.</div>`}
function filteredTools(q){let list=tools.filter(t=>`${t.name} ${t.description} ${t.category}`.toLowerCase().includes(q.toLowerCase()));if(category==="Favoritos")list=list.filter(t=>state.favorites.has(t.id));else if(category==="Recentes"){const pos=new Map(state.recent.map((id,i)=>[id,i]));list=list.filter(t=>pos.has(t.id)).sort((x,y)=>pos.get(x.id)-pos.get(y.id))}else if(category==="Mais usados")list=list.filter(t=>(state.usage[t.id]||0)>0).sort((x,y)=>(state.usage[y.id]||0)-(state.usage[x.id]||0));else if(category!=="Todos")list=list.filter(t=>t.category===category);return list}
function projectsView(){return `<div class="hero"><span class="eyebrow">Workspaces</span><h1>Projetos</h1><p>Central de acesso aos produtos e ambientes da States Softwares.</p></div><div class="grid project-grid">${projects.map(p=>`<article class="card project-card"><div class="project-top"><div class="project-mark">${esc(p.name.slice(0,2).toUpperCase())}</div><span class="project-status">${esc(p.status)}</span></div><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p><div class="project-links">${p.links.map(l=>`<a href="${l[1]}" target="_blank" rel="noopener noreferrer">${esc(l[0])} ↗</a>`).join("")}</div></article>`).join("")}</div>`}
function qrView(){return `<div class="hero"><span class="eyebrow">Utilitário nativo</span><h1>QR Code</h1><p>Gere um QR Code sem sair do seu workspace.</p></div><div class="qr-layout"><form class="card qr-form" id="qrForm"><label>Texto ou URL</label><input class="search" id="qrText" placeholder="https://..." required><label>Tamanho</label><select id="qrSize"><option>256</option><option selected>512</option><option>768</option><option>1024</option></select><button class="primary">Gerar QR Code</button></form><article class="card qr-preview"><div id="qrOutput"><span>Seu QR aparecerá aqui</span></div><a id="qrDownload" class="primary download-link" hidden download="tools-digital-qr.png">Baixar PNG</a></article></div>`}
function flowView(){return `<div class="flow-page"><div class="hero flow-hero"><span class="eyebrow">Canvas Workspace</span><h1>Fluxo Tools</h1><p>Mapeie ideias, arquitetura, processos e integrações dentro do Tools Digital.</p></div><div id="flowMount"></div></div>`}
const ensureLocalIds=()=>{let changed=false;state.notes=state.notes.map(n=>{if(n.id)return n;changed=true;return{...n,id:crypto.randomUUID?.()||Date.now()+"-"+Math.random()}});state.transactions=state.transactions.map(t=>{if(t.id)return t;changed=true;return{...t,id:crypto.randomUUID?.()||Date.now()+"-"+Math.random(),category:t.category||"Geral"}});if(changed){store.set("td:notes",state.notes);store.set("td:transactions",state.transactions)}};ensureLocalIds();
function notesView(){return `<div class="module-head"><div class="hero"><span class="eyebrow">Workspace</span><h1>Notas</h1><p>Capture ideias, decisões e lembretes dentro do workspace.</p></div><button class="primary" id="newNoteBtn">＋ Nova nota</button></div><div class="module-toolbar"><div class="tool-search-wrap">⌕<input class="search" id="noteSearch" placeholder="Pesquisar notas..."></div><span>${state.notes.length} notas</span></div><div class="grid notes-grid" id="notesGrid">${renderNotes(state.notes)}</div><div class="tools-empty" id="notesEmpty" ${state.notes.length?"hidden":""}>Nenhuma nota ainda.</div>`}
function renderNotes(list){return list.map(n=>`<article class="card note-card" data-note="${n.id}"><div class="note-top"><small>${new Date(n.createdAt).toLocaleDateString("pt-BR")}</small><button data-note-menu="${n.id}" aria-label="Editar nota">•••</button></div><h3>${esc(n.title||"Sem título")}</h3><p>${esc(n.body||"")}</p></article>`).join("")}
async function noteDialog(note=null){if(!window.Swal)return;const r=await Swal.fire({title:note?"Editar nota":"Nova nota",html:`<input id="swNoteTitle" class="swal2-input" maxlength="100" placeholder="Título" value="${esc(note?.title||"")}"><textarea id="swNoteBody" class="swal2-textarea" maxlength="3000" placeholder="Escreva sua nota...">${esc(note?.body||"")}</textarea>`,showCancelButton:true,confirmButtonText:note?"Salvar alterações":"Salvar nota",cancelButtonText:"Cancelar",background:"#080808",color:"#fff",confirmButtonColor:"#fff",preConfirm:()=>{const title=document.querySelector("#swNoteTitle").value.trim(),body=document.querySelector("#swNoteBody").value.trim();if(!title&&!body){Swal.showValidationMessage("Escreva um título ou conteúdo");return false}return{title,body}}});if(!r.isConfirmed)return;if(note){note.title=r.value.title;note.body=r.value.body;note.updatedAt=Date.now()}else state.notes.unshift({id:crypto.randomUUID?.()||String(Date.now()),...r.value,createdAt:Date.now()});store.set("td:notes",state.notes);toast(note?"Nota atualizada":"Nota criada");render()}
async function noteMenu(id){const n=state.notes.find(x=>x.id===id);if(!n)return;const r=await Swal.fire({title:n.title||"Nota",showDenyButton:true,showCancelButton:true,confirmButtonText:"Editar",denyButtonText:"Excluir",cancelButtonText:"Fechar",background:"#080808",color:"#fff",confirmButtonColor:"#fff",denyButtonColor:"#3a1010"});if(r.isConfirmed)noteDialog(n);else if(r.isDenied){const ok=await Swal.fire({title:"Excluir nota?",text:"Esta ação não poderá ser desfeita.",icon:"warning",showCancelButton:true,confirmButtonText:"Excluir",cancelButtonText:"Cancelar",background:"#080808",color:"#fff",confirmButtonColor:"#fff"});if(ok.isConfirmed){state.notes=state.notes.filter(x=>x.id!==id);store.set("td:notes",state.notes);toast("Nota excluída");render()}}}
const money=v=>(v/100).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
function financeView(){const inc=state.transactions.filter(x=>x.amount>0).reduce((a,b)=>a+b.amount,0),out=state.transactions.filter(x=>x.amount<0).reduce((a,b)=>a+b.amount,0);return `<div class="module-head"><div class="hero"><span class="eyebrow">Controle local</span><h1>Financeiro</h1><p>Registre entradas e saídas sem sair do workspace.</p></div><button class="primary" id="newTxBtn">＋ Nova transação</button></div><div class="grid finance-summary"><article class="card"><p>Entradas</p><div class="money positive">${money(inc)}</div></article><article class="card"><p>Saídas</p><div class="money negative">${money(out)}</div></article><article class="card"><p>Saldo</p><div class="money">${money(inc+out)}</div></article></div><div class="module-toolbar finance-toolbar"><div class="tool-search-wrap">⌕<input class="search" id="txSearch" placeholder="Pesquisar transação..."></div><select id="txFilter"><option value="all">Todas</option><option value="in">Entradas</option><option value="out">Saídas</option></select></div><div id="txList">${renderTransactions(state.transactions)}</div><div class="tools-empty" id="txEmpty" ${state.transactions.length?"hidden":""}>Nenhuma transação encontrada.</div>`}
function renderTransactions(list){return list.map(t=>`<article class="card transaction" data-tx="${t.id}"><div><span class="tx-category">${esc(t.category||"Geral")}</span><h3>${esc(t.description)}</h3><p>${new Date(t.createdAt).toLocaleDateString("pt-BR")}</p></div><div class="tx-value"><strong class="${t.amount>=0?"positive":"negative"}">${money(t.amount)}</strong><button data-tx-menu="${t.id}" aria-label="Editar transação">•••</button></div></article>`).join("")}
async function txDialog(tx=null){if(!window.Swal)return;const r=await Swal.fire({title:tx?"Editar transação":"Nova transação",html:`<input id="swTxDesc" class="swal2-input" maxlength="120" placeholder="Descrição" value="${esc(tx?.description||"")}"><input id="swTxAmount" class="swal2-input" type="number" step="0.01" placeholder="Valor: negativo = saída" value="${tx?tx.amount/100:""}"><input id="swTxCategory" class="swal2-input" maxlength="40" placeholder="Categoria" value="${esc(tx?.category||"Geral")}">`,showCancelButton:true,confirmButtonText:tx?"Salvar alterações":"Adicionar",cancelButtonText:"Cancelar",background:"#080808",color:"#fff",confirmButtonColor:"#fff",preConfirm:()=>{const description=document.querySelector("#swTxDesc").value.trim(),amount=Math.round(Number(document.querySelector("#swTxAmount").value)*100),category=document.querySelector("#swTxCategory").value.trim()||"Geral";if(!description||!Number.isFinite(amount)||amount===0){Swal.showValidationMessage("Informe descrição e um valor diferente de zero");return false}return{description,amount,category}}});if(!r.isConfirmed)return;if(tx){Object.assign(tx,r.value,{updatedAt:Date.now()})}else state.transactions.unshift({id:crypto.randomUUID?.()||String(Date.now()),...r.value,createdAt:Date.now()});store.set("td:transactions",state.transactions);toast(tx?"Transação atualizada":"Transação adicionada");render()}
async function txMenu(id){const t=state.transactions.find(x=>x.id===id);if(!t)return;const r=await Swal.fire({title:t.description,showDenyButton:true,showCancelButton:true,confirmButtonText:"Editar",denyButtonText:"Excluir",cancelButtonText:"Fechar",background:"#080808",color:"#fff",confirmButtonColor:"#fff",denyButtonColor:"#3a1010"});if(r.isConfirmed)txDialog(t);else if(r.isDenied){const ok=await Swal.fire({title:"Excluir transação?",icon:"warning",showCancelButton:true,confirmButtonText:"Excluir",cancelButtonText:"Cancelar",background:"#080808",color:"#fff",confirmButtonColor:"#fff"});if(ok.isConfirmed){state.transactions=state.transactions.filter(x=>x.id!==id);store.set("td:transactions",state.transactions);toast("Transação excluída");render()}}}
function render(){const v=$("#view");v.innerHTML=view==="dashboard"?dashboard():view==="tools"?toolsView():view==="projects"?projectsView():view==="qrcode"?qrView():view==="flow"?flowView():view==="notes"?notesView():financeView();bind()}
function goTo(next){view=next;document.querySelectorAll("[data-view]").forEach(x=>x.classList.toggle("active",x.dataset.view===view));$("#sidebar")?.classList.remove("open");render()}
document.querySelectorAll("[data-view]").forEach(x=>x.classList.toggle("active",x.dataset.view===view));$("#sidebar")?.classList.remove("open");render()}
function bind(){document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>goTo(b.dataset.go));document.querySelectorAll('[data-action="command"]').forEach(b=>b.onclick=openCommand);if(view==="flow"){const mount=$("#flowMount");if(mount)mountFlow(mount,{store,onNotify:toast})}const qrForm=$("#qrForm");if(qrForm)qrForm.addEventListener("submit",e=>{e.preventDefault();const text=$("#qrText").value.trim(),size=$("#qrSize").value;if(!text)return;const url=`https://api.qrserver.com/v1/create-qr-code/?size=${size}x${size}&data=${encodeURIComponent(text)}&color=ffffff&bgcolor=000000&margin=16`;$("#qrOutput").innerHTML=`<img src="${url}" alt="QR Code gerado">`;const d=$("#qrDownload");d.href=url;d.hidden=false;});const viewEl=$("#view");viewEl.onclick=e=>{const fav=e.target.closest("[data-fav]");if(fav){e.stopPropagation();state.favorites.has(fav.dataset.fav)?state.favorites.delete(fav.dataset.fav):state.favorites.add(fav.dataset.fav);store.set("td:favorites",[...state.favorites]);render();return}const card=e.target.closest("[data-open]");if(card)openTool(card.dataset.open)};viewEl.onkeydown=e=>{const card=e.target.closest("[data-open]");if(card&&(e.key==="Enter"||e.key===" ")){e.preventDefault();openTool(card.dataset.open)}};document.querySelectorAll("[data-cat]").forEach(b=>b.onclick=()=>{category=b.dataset.cat;render()});const toolSearch=$("#toolSearch");const paintTools=()=>{const list=filteredTools(toolSearch?.value||"");$("#toolGrid").innerHTML=list.map(toolCard).join("");$("#toolCount").textContent=list.length+" resultados";$("#toolsEmpty").hidden=!!list.length};toolSearch?.addEventListener("input",paintTools);$("#clearToolFilters")?.addEventListener("click",()=>{category="Todos";if(toolSearch)toolSearch.value="";render()});$("#noteForm")?.addEventListener("submit",e=>{e.preventDefault();state.notes.unshift({title:$("#noteTitle").value.trim(),body:$("#noteBody").value.trim(),createdAt:Date.now()});store.set("td:notes",state.notes);toast("Nota salva");render()});document.querySelectorAll("[data-del-note]").forEach(b=>b.onclick=()=>{state.notes.splice(+b.dataset.delNote,1);store.set("td:notes",state.notes);render()});$("#financeForm")?.addEventListener("submit",e=>{e.preventDefault();const amount=Math.round(Number($("#txAmount").value)*100);if(!Number.isFinite(amount)||amount===0)return;state.transactions.unshift({description:$("#txDesc").value.trim(),amount,createdAt:Date.now()});store.set("td:transactions",state.transactions);toast("Transação adicionada");render()});document.querySelectorAll("[data-del-tx]").forEach(b=>b.onclick=()=>{state.transactions.splice(+b.dataset.delTx,1);store.set("td:transactions",state.transactions);render()})}
document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>goTo(b.dataset.view));$("#menuBtn").onclick=()=>$("#sidebar").classList.toggle("open");const moreBtn=$("#moreBtn"),moreSheet=$("#moreSheet");if(moreBtn&&moreSheet){moreBtn.onclick=()=>{moreSheet.hidden=!moreSheet.hidden};moreSheet.querySelectorAll("[data-view]").forEach(b=>b.addEventListener("click",()=>{moreSheet.hidden=true}))}
function toast(message,icon="success"){if(window.Swal){Swal.fire({toast:true,position:"top-end",icon,title:message,showConfirmButton:false,timer:1800,timerProgressBar:true,background:"#080808",color:"#fff"});return}const t=$("#toast");t.textContent=message;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1800)}
const overlay=$("#commandOverlay"),input=$("#commandInput"),results=$("#commandResults"),modules=[["dashboard","Início","Workspace"],["tools","Ferramentas","Módulo"],["projects","Projetos","Módulo"],["flow","Fluxo Tools","Módulo"],["qrcode","QR Code","Módulo"],["notes","Notas","Módulo"],["finance","Financeiro","Módulo"]];let commandIndex=0,commandItems=[];
function command(q=""){const term=q.trim().toLowerCase(),mods=modules.filter(x=>!term||(`${x[1]} ${x[2]}`).toLowerCase().includes(term)).map(x=>({kind:"module",id:x[0],name:x[1],meta:x[2]})),ts=tools.filter(t=>!term||(`${t.name} ${t.category} ${t.description}`).toLowerCase().includes(term)).sort((a,b)=>(state.usage[b.id]||0)-(state.usage[a.id]||0)).slice(0,10).map(t=>({kind:"tool",id:t.id,name:t.name,meta:t.category+" · "+t.description}));commandItems=[...mods,...ts].slice(0,12);commandIndex=0;results.innerHTML=commandItems.length?commandItems.map((x,i)=>`<div class="command-result ${i===0?"selected":""}" data-command-index="${i}"><i>${x.kind==="module"?"⌘":"↗"}</i><div><strong>${esc(x.name)}</strong><p>${esc(x.meta)}</p></div></div>`).join(""):`<div class="command-empty">Nenhum resultado encontrado</div>`;results.querySelectorAll("[data-command-index]").forEach(x=>x.onclick=()=>runCommand(+x.dataset.commandIndex))}
function paintCommandSelection(){results.querySelectorAll("[data-command-index]").forEach((x,i)=>{x.classList.toggle("selected",i===commandIndex);if(i===commandIndex)x.scrollIntoView({block:"nearest"})})}
function runCommand(i=commandIndex){const x=commandItems[i];if(!x)return;x.kind==="module"?goTo(x.id):openTool(x.id);closeCommand()}
function openCommand(){overlay.hidden=false;input.value="";command();setTimeout(()=>input.focus(),0)}
function closeCommand(){overlay.hidden=true}
$("#commandBtn").onclick=openCommand;input.oninput=e=>command(e.target.value);document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();openCommand();return}if(overlay.hidden)return;if(e.key==="Escape"){closeCommand();return}if(e.key==="ArrowDown"){e.preventDefault();commandIndex=Math.min(commandIndex+1,commandItems.length-1);paintCommandSelection()}else if(e.key==="ArrowUp"){e.preventDefault();commandIndex=Math.max(commandIndex-1,0);paintCommandSelection()}else if(e.key==="Enter"){e.preventDefault();runCommand()}});overlay.onclick=e=>{if(e.target===overlay)closeCommand()};
const APP_VERSION="2.8.0";let swRegistration=null,refreshing=false;
$("#appVersion").textContent="Tools Digital v"+APP_VERSION;
async function updatePrompt(worker){if(!worker)return;const ok=window.Swal?(await Swal.fire({title:"Nova atualização disponível",text:"Uma nova versão do Tools Digital está pronta para instalar.",icon:"info",showCancelButton:true,confirmButtonText:"Atualizar agora",cancelButtonText:"Depois",background:"#080808",color:"#fff",confirmButtonColor:"#fff"})).isConfirmed:confirm("Nova atualização disponível. Atualizar agora?");if(ok)worker.postMessage({type:"SKIP_WAITING"})}
async function checkForUpdates(manual=false){if(!swRegistration){if(manual)toast("Verificação de atualização indisponível","error");return}const label=$("#updateLabel");if(label)label.textContent="Verificando...";try{await swRegistration.update();if(swRegistration.waiting){await updatePrompt(swRegistration.waiting)}else if(manual){toast("Você já está na versão mais recente","success")}}catch{if(manual)toast("Não foi possível buscar atualizações","error")}finally{if(label)label.textContent="Buscar atualizações"}}
$("#updateBtn")?.addEventListener("click",()=>checkForUpdates(true));
if("serviceWorker"in navigator)window.addEventListener("load",async()=>{try{swRegistration=await navigator.serviceWorker.register("./sw.js",{updateViaCache:"none"});if(swRegistration.waiting)updatePrompt(swRegistration.waiting);swRegistration.addEventListener("updatefound",()=>{const w=swRegistration.installing;if(!w)return;w.addEventListener("statechange",()=>{if(w.state==="installed"&&navigator.serviceWorker.controller)updatePrompt(w)})});navigator.serviceWorker.addEventListener("controllerchange",()=>{if(refreshing)return;refreshing=true;location.reload()});setTimeout(()=>checkForUpdates(false),1500)}catch{}});
document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible"&&swRegistration)checkForUpdates(false)});
window.addEventListener("online",()=>{if(swRegistration)checkForUpdates(false)});
render();