import{tools}from"./data/tools.js";
import{mountFlow}from"./modules/flow-tools.js";
const $=s=>document.querySelector(s),store={get:(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set:(k,v)=>localStorage.setItem(k,JSON.stringify(v))};
let view="dashboard",category="Todos";
const projects=[
{name:"Diamond Game",status:"Em desenvolvimento",description:"Plataforma 1x1 competitiva",links:[["Frontend","https://github.com/CarlosDevITT/Diamond-Game"],["Servidor","https://github.com/CarlosDevITT/Diamond-Game-Server"],["Appwrite","https://cloud.appwrite.io"],["Railway","https://railway.com"]]},
{name:"Ignite Restaurante",status:"Operacional",description:"Cardápio digital, PDV e PWA",links:[["Vercel","https://ignite-restaurant-kappa.vercel.app"],["Supabase","https://supabase.com/dashboard"]]},
{name:"States Service",status:"Em desenvolvimento",description:"Ecossistema de serviços States Softwares",links:[["GitHub","https://github.com/CarlosDevITT/States-All"],["Supabase","https://supabase.com/dashboard"]]}
];
const state={favorites:new Set(store.get("td:favorites",[])),recent:store.get("td:recent",[]),notes:store.get("td:notes",[]),transactions:store.get("td:transactions",[])};
const esc=s=>{const d=document.createElement("div");d.textContent=s??"";return d.innerHTML};
function toolCard(t){return `<article class="card tool-card" data-open="${t.id}"><button class="fav ${state.favorites.has(t.id)?"on":""}" data-fav="${t.id}" aria-label="Favoritar">★</button><div class="tool-icon">${esc(t.icon)}</div><h3>${esc(t.name)}</h3><p>${esc(t.description)}</p></article>`}
function openTool(id){const t=tools.find(x=>x.id===id);if(!t)return;state.recent=[id,...state.recent.filter(x=>x!==id)].slice(0,8);store.set("td:recent",state.recent);window.open(t.url,"_blank","noopener,noreferrer")}
function dashboard(){const fav=tools.filter(t=>state.favorites.has(t.id));const recent=state.recent.map(id=>tools.find(t=>t.id===id)).filter(Boolean);return `<div class="hero"><span class="eyebrow">Tools Digital V2</span><h1>Seu trabalho, centralizado.</h1><p>Ferramentas, notas e operação em um workspace rápido. Use Ctrl + K para ir direto ao que precisa.</p></div><div class="section-head"><h2>Favoritos</h2><span>${fav.length} ferramentas</span></div><div class="grid">${(fav.length?fav:tools.slice(0,4)).map(toolCard).join("")}</div><div class="section-head"><h2>Recentes</h2><span>acesso rápido</span></div><div class="grid">${(recent.length?recent:tools.slice(4,8)).map(toolCard).join("")}</div>`}
function toolsView(){const cats=["Todos",...new Set(tools.map(t=>t.category))];return `<div class="hero"><span class="eyebrow">Biblioteca</span><h1>Ferramentas</h1><p>Pesquise, filtre e favorite suas ferramentas de trabalho.</p></div><input class="search" id="toolSearch" placeholder="Pesquisar ferramenta..."><div class="filters">${cats.map(c=>`<button class="chip ${c===category?"active":""}" data-cat="${c}">${c}</button>`).join("")}</div><div class="grid" id="toolGrid">${filteredTools("").map(toolCard).join("")}</div>`}
function filteredTools(q){return tools.filter(t=>(category==="Todos"||t.category===category)&&(`${t.name} ${t.description} ${t.category}`).toLowerCase().includes(q.toLowerCase()))}
function projectsView(){return `<div class="hero"><span class="eyebrow">Workspaces</span><h1>Projetos</h1><p>Central de acesso aos produtos e ambientes da States Softwares.</p></div><div class="grid project-grid">${projects.map(p=>`<article class="card project-card"><div class="project-top"><div class="project-mark">${esc(p.name.slice(0,2).toUpperCase())}</div><span class="project-status">${esc(p.status)}</span></div><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p><div class="project-links">${p.links.map(l=>`<a href="${l[1]}" target="_blank" rel="noopener noreferrer">${esc(l[0])} ↗</a>`).join("")}</div></article>`).join("")}</div>`}
function qrView(){return `<div class="hero"><span class="eyebrow">Utilitário nativo</span><h1>QR Code</h1><p>Gere um QR Code sem sair do seu workspace.</p></div><div class="qr-layout"><form class="card qr-form" id="qrForm"><label>Texto ou URL</label><input class="search" id="qrText" placeholder="https://..." required><label>Tamanho</label><select id="qrSize"><option>256</option><option selected>512</option><option>768</option><option>1024</option></select><button class="primary">Gerar QR Code</button></form><article class="card qr-preview"><div id="qrOutput"><span>Seu QR aparecerá aqui</span></div><a id="qrDownload" class="primary download-link" hidden download="tools-digital-qr.png">Baixar PNG</a></article></div>`}
function flowView(){return `<div class="flow-page"><div class="hero flow-hero"><span class="eyebrow">Canvas Workspace</span><h1>Fluxo Tools</h1><p>Mapeie ideias, arquitetura, processos e integrações dentro do Tools Digital.</p></div><div id="flowMount"></div></div>`}
function notesView(){return `<div class="hero"><span class="eyebrow">Workspace</span><h1>Notas</h1><p>Notas rápidas salvas neste dispositivo.</p></div><form class="note-form" id="noteForm"><input id="noteTitle" maxlength="100" placeholder="Título"><textarea id="noteBody" maxlength="3000" placeholder="Escreva sua nota..."></textarea><button class="primary">Salvar nota</button></form><div class="grid">${state.notes.map((n,i)=>`<article class="card note-card"><h3>${esc(n.title||"Sem título")}</h3><p>${esc(n.body)}</p><br><button class="danger" data-del-note="${i}">Excluir</button></article>`).join("")}</div>`}
const money=v=>(v/100).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
function financeView(){const inc=state.transactions.filter(x=>x.amount>0).reduce((a,b)=>a+b.amount,0),out=state.transactions.filter(x=>x.amount<0).reduce((a,b)=>a+b.amount,0);return `<div class="hero"><span class="eyebrow">Controle</span><h1>Financeiro</h1><p>Controle local simplificado. Backend multiusuário entra na próxima camada.</p></div><div class="grid finance-summary"><article class="card"><p>Entradas</p><div class="money positive">${money(inc)}</div></article><article class="card"><p>Saídas</p><div class="money negative">${money(out)}</div></article><article class="card"><p>Saldo</p><div class="money">${money(inc+out)}</div></article></div><form class="finance-form" id="financeForm"><input id="txDesc" maxlength="120" placeholder="Descrição" required><input id="txAmount" type="number" step="0.01" placeholder="Valor (use negativo para saída)" required><button class="primary">Adicionar transação</button></form><div>${state.transactions.map((t,i)=>`<article class="card transaction"><div><h3>${esc(t.description)}</h3><p>${new Date(t.createdAt).toLocaleDateString("pt-BR")}</p></div><div><strong class="${t.amount>=0?"positive":"negative"}">${money(t.amount)}</strong> <button class="danger" data-del-tx="${i}">×</button></div></article>`).join("")}</div>`}
function render(){const v=$("#view");v.innerHTML=view==="dashboard"?dashboard():view==="tools"?toolsView():view==="projects"?projectsView():view==="qrcode"?qrView():view==="flow"?flowView():view==="notes"?notesView():financeView();bind()}
function bind(){if(view==="flow"){const mount=$("#flowMount");if(mount)mountFlow(mount,{store,onNotify:toast})}const qrForm=$("#qrForm");if(qrForm)qrForm.addEventListener("submit",e=>{e.preventDefault();const text=$("#qrText").value.trim(),size=$("#qrSize").value;if(!text)return;const url=`https://api.qrserver.com/v1/create-qr-code/?size=${size}x${size}&data=${encodeURIComponent(text)}&color=ffffff&bgcolor=000000&margin=16`;$("#qrOutput").innerHTML=`<img src="${url}" alt="QR Code gerado">`;const d=$("#qrDownload");d.href=url;d.hidden=false;});document.querySelectorAll("[data-open]").forEach(x=>x.onclick=e=>{if(e.target.closest("[data-fav]"))return;openTool(x.dataset.open)});document.querySelectorAll("[data-fav]").forEach(b=>b.onclick=()=>{state.favorites.has(b.dataset.fav)?state.favorites.delete(b.dataset.fav):state.favorites.add(b.dataset.fav);store.set("td:favorites",[...state.favorites]);render()});document.querySelectorAll("[data-cat]").forEach(b=>b.onclick=()=>{category=b.dataset.cat;render()});$("#toolSearch")?.addEventListener("input",e=>$("#toolGrid").innerHTML=filteredTools(e.target.value).map(toolCard).join(""));$("#noteForm")?.addEventListener("submit",e=>{e.preventDefault();state.notes.unshift({title:$("#noteTitle").value.trim(),body:$("#noteBody").value.trim(),createdAt:Date.now()});store.set("td:notes",state.notes);toast("Nota salva");render()});document.querySelectorAll("[data-del-note]").forEach(b=>b.onclick=()=>{state.notes.splice(+b.dataset.delNote,1);store.set("td:notes",state.notes);render()});$("#financeForm")?.addEventListener("submit",e=>{e.preventDefault();const amount=Math.round(Number($("#txAmount").value)*100);if(!Number.isFinite(amount)||amount===0)return;state.transactions.unshift({description:$("#txDesc").value.trim(),amount,createdAt:Date.now()});store.set("td:transactions",state.transactions);toast("Transação adicionada");render()});document.querySelectorAll("[data-del-tx]").forEach(b=>b.onclick=()=>{state.transactions.splice(+b.dataset.delTx,1);store.set("td:transactions",state.transactions);render()})}
document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>{view=b.dataset.view;document.querySelectorAll("[data-view]").forEach(x=>x.classList.toggle("active",x.dataset.view===view));$("#sidebar").classList.remove("open");render()});$("#menuBtn").onclick=()=>$("#sidebar").classList.toggle("open");
function toast(message,icon="success"){if(window.Swal){Swal.fire({toast:true,position:"top-end",icon,title:message,showConfirmButton:false,timer:1800,timerProgressBar:true,background:"#080808",color:"#fff"});return}const t=$("#toast");t.textContent=message;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1800)}
const overlay=$("#commandOverlay"),input=$("#commandInput"),results=$("#commandResults");function command(q=""){const matches=tools.filter(t=>t.name.toLowerCase().includes(q.toLowerCase())).slice(0,8);results.innerHTML=matches.map((t,i)=>`<div class="command-result ${i===0?"selected":""}" data-command="${t.id}"><strong>${esc(t.name)}</strong><p>${esc(t.category)} · ${esc(t.description)}</p></div>`).join("");document.querySelectorAll("[data-command]").forEach(x=>x.onclick=()=>{openTool(x.dataset.command);closeCommand()})}function openCommand(){overlay.hidden=false;input.value="";command();setTimeout(()=>input.focus(),0)}function closeCommand(){overlay.hidden=true}$("#commandBtn").onclick=openCommand;input.oninput=e=>command(e.target.value);document.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();openCommand()}if(e.key==="Escape")closeCommand();if(e.key==="Enter"&&!overlay.hidden){const s=$(".command-result");if(s){openTool(s.dataset.command);closeCommand()}}});overlay.onclick=e=>{if(e.target===overlay)closeCommand()};if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));render();